export const PRODUCTIVITY_QUOTES = [
    { quote: "No nos atrevemos a muchas cosas porque son difíciles, pero son difíciles porque no nos atrevemos a hacerlas.", author: "Séneca" },
    { quote: "Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto y encontrarás tu fuerza.", author: "Marco Aurelio" },
    { quote: "No pierdas más tiempo discutiendo lo que debe ser un buen hombre. Sé uno.", author: "Marco Aurelio" },
    { quote: "La felicidad de tu vida depende de la calidad de tus pensamientos.", author: "Marco Aurelio" },
    { quote: "Sufrimos más a menudo en la imaginación que en la realidad.", author: "Séneca" },
    { quote: "Primero dite a ti mismo lo que serías; y luego haz lo que tienes que hacer.", author: "Epicteto" },
    { quote: "No busques que los eventos sucedan como quieres, sino desea que sucedan como sí suceden.", author: "Epicteto" },
    { quote: "El hombre que mueve una montaña comienza llevándose piedras pequeñas.", author: "Confucio" },
    { quote: "Tu nivel de éxito rara vez superará tu nivel de desarrollo personal.", author: "Jim Rohn" },
    { quote: "Haz siempre un esfuerzo total, aun cuando las probabilidades están en contra tuya.", author: "Arnold Palmer" },
    { quote: "El secreto de salir adelante es empezar.", author: "Mark Twain" },
    { quote: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { quote: "Si amas la vida, no pierdas el tiempo, porque el tiempo es de lo que está hecha la vida.", author: "Bruce Lee" },
    { quote: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    { quote: "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.", author: "Jack Canfield" },
    { quote: "Actúa como si lo que haces marcara la diferencia. Lo hace.", author: "William James" },
    { quote: "No es que tengamos poco tiempo, es que perdemos mucho.", author: "Séneca" },
    { quote: "La clave no es gastar el tiempo, sino invertirlo.", author: "Stephen R. Covey" },
    { quote: "Sólo yo puedo cambiar mi vida. Nadie puede hacerlo por mí.", author: "Carol Burnett" },
    { quote: "Lo que hacemos durante nuestras horas de trabajo determina lo que tenemos; lo que hacemos en nuestras horas de ocio determina lo que somos.", author: "George Eastman" },
    { quote: "Concéntrate en el viaje, no en el destino. La alegría se encuentra no en terminar una actividad, sino en hacerla.", author: "Greg Anderson" },
    { quote: "El perfeccionismo es el enemigo de la creación, al igual que el peor enemigo del bien es lo mejor.", author: "John Updike" },
    { quote: "Nunca te rindas en un sueño sólo por el tiempo que tomará lograrlo. El tiempo pasará de todos modos.", author: "Earl Nightingale" },
    { quote: "Nuestra mayor debilidad radica en rendirnos. La forma más segura de tener éxito es siempre intentarlo una vez más.", author: "Thomas A. Edison" },
    { quote: "Conquista al que se enoja no enojándote tú; conquista al malo con la bondad.", author: "Buda" },
    { quote: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.", author: "Henry Ford" },
    { quote: "Si no diseñas tu propio plan de vida, lo más probable es que caigas en el plan de otra persona.", author: "Jim Rohn" },
    { quote: "Para lograr grandes cosas, no solo debemos actuar, sino también soñar; no solo planear, sino también creer.", author: "Anatole France" },
    { quote: "La suerte es un dividendo del sudor. Cuanto más sudes, más suerte tendrás.", author: "Ray Kroc" },
    { quote: "A veces, las cosas más ordinarias podrían hacerse extraordinarias, simplemente haciéndolas con las personas adecuadas.", author: "Elizabeth Green" },
    { quote: "Hacer dos cosas a la vez es no hacer ninguna.", author: "Publilio Siro" },
    { quote: "Productividad nunca es un accidente. Siempre es el resultado de un compromiso con la excelencia.", author: "Paul J. Meyer" },
    { quote: "Mejorar es cambiar; ser perfecto es cambiar a menudo.", author: "Winston Churchill" },
    { quote: "Las cosas no suceden. Las cosas se hacen.", author: "John F. Kennedy" },
    { quote: "Ama lo que tienes, pero nunca dejes de buscar lo que necesitas.", author: "Lao Tsé" },
    { quote: "Si quieres vivir una vida feliz, átala a una meta, no a personas o cosas.", author: "Albert Einstein" },
    { quote: "La disciplina es el puente entre las metas y el logro", author: "Jim Rohn" },
    { quote: "Tanto si piensas que puedes como si piensas que no puedes, estás en lo cierto.", author: "Henry Ford" },
    { quote: "Aquellos que no pueden cambiar de opinión, no pueden cambiar nada.", author: "George Bernard Shaw" },
    { quote: "Tómate tu tiempo para deliberar; pero cuando llegue el momento de actuar, deja de pensar y entra.", author: "Andrew Jackson" },
    { quote: "Hecho es mejor que perfecto.", author: "Sheryl Sandberg" },
    { quote: "Un año a partir de ahora, desearás haber comenzado hoy.", author: "Karen Lamb" },
    { quote: "La forma de empezar es dejar de hablar y empezar a hacerlo.", author: "Walt Disney" },
    { quote: "Es posible cometer cero errores e igual perder. Eso no es debilidad, es la vida.", author: "Jean-Luc Picard" },
    { quote: "La vida es un 10\% lo que te sucede y un 90\% cómo reaccionas ante ello.", author: "Charles R. Swindoll" },
    { quote: "Recuerda que a veces no conseguir lo que quieres es una maravillosa suerte.", author: "Dalai Lama" },
    { quote: "Solo existen dos días en el año en que no se puede hacer nada. Uno se llama ayer y otro mañana.", author: "Dalai Lama" },
    { quote: "Sé el cambio que deseas ver en el mundo.", author: "Mahatma Gandhi" },
    { quote: "Haz una cosa cada día que te asuste.", author: "Eleanor Roosevelt" },
    { quote: "No somos lo que sabemos, somos lo que estamos dispuestos a aprender.", author: "Mary Catherine Bateson" }
];
